### ISSUE TITLE
jison-gho on NPM contains unrelated files

### ISSUE THREAD

**Issue by evgeni** [GerHobbelt/jison#43] opened 2019-01-17 12:52 UTC
Ohai,

`jison-gho` (0.6.1-215)  on NPM contains (IMHO) unrelated files, that account for about of 21MB of data.
They are all in the `tmp2` folder:

```
tmp2
└── sandbox
    ├── Coding the matrix
    │   ├── l01_fields
    │   │   ├── 01 - fields.ipynb
    │   │   ├── __init__.py
    │   │   ├── inverse_index_lab.py
    │   │   ├── profile.txt
    │   │   ├── python_lab.py
    │   │   ├── stories_big.txt
    │   │   ├── stories_small.txt
    │   │   ├── submit.py
    │   │   ├── The_Field_problems.py
    │   │   └── The_Function_problems.py
    │   ├── l02_vectors
    │   │   ├── 02 - vectors.ipynb
    │   │   ├── GF2.py
    │   │   ├── __init__.py
    │   │   ├── politics_lab.py
    │   │   ├── profile.txt
    │   │   ├── submit.py
    │   │   ├── test_vec.py
    │   │   ├── The_Vector_problems.py
    │   │   ├── The_Vector_Space_problems.py
    │   │   ├── UN_voting_data.txt
    │   │   ├── US_Senate_voting_data_109.txt
    │   │   ├── vec.py
    │   │   ├── vecutil.py
    │   │   └── voting_record_dump109.txt
    │   ├── l03_matrix
    │   │   ├── bitutil.py
    │   │   ├── cit.png
    │   │   ├── ecc_lab.py
    │   │   ├── geometry_lab.py
    │   │   ├── __init__.py
    │   │   ├── l03_matrix.ipynb
    │   │   ├── mat.py
    │   │   ├── mat_sparsity.py
    │   │   ├── profile.txt
    │   │   ├── submit.py
    │   │   ├── The_Matrix_problems.py
    │   │   └── UN_voting_data.txt
    │   ├── l04_basis
    │   │   ├── board.png
    │   │   ├── cit.png
    │   │   ├── __init__.py
    │   │   ├── l04_basis.ipynb
    │   │   ├── perspective_lab.py
    │   │   ├── profile.txt
    │   │   ├── submit.py
    │   │   └── The_Basis_problems.py
    │   ├── l05_dimension
    │   │   ├── Dimension_problems.py
    │   │   ├── independence.py
    │   │   ├── l05_dimension.ipynb
    │   │   └── triangular.py
    │   └── matlib
    │       ├── basutil.py
    │       ├── bitutil.py
    │       ├── dictutil.py
    │       ├── GF2.py
    │       ├── image_mat_util.py
    │       ├── image.py
    │       ├── img01.png
    │       ├── __init__.py
    │       ├── mat.py
    │       ├── matutil.py
    │       ├── plotting.py
    │       ├── png.py
    │       ├── solver.py
    │       ├── vec.py
    │       └── vecutil.py
    ├── HTML
    │   ├── [Habr] Single-page layout 1 (simple)
    │   │   ├── apple-touch-icon.png
    │   │   ├── css
    │   │   │   ├── main.css
    │   │   │   ├── normalize.css
    │   │   │   └── styles.css
    │   │   ├── doc
    │   │   │   ├── css.md
    │   │   │   ├── extend.md
    │   │   │   ├── faq.md
    │   │   │   ├── html.md
    │   │   │   ├── js.md
    │   │   │   ├── misc.md
    │   │   │   ├── TOC.md
    │   │   │   └── usage.md
    │   │   ├── favicon.ico
    │   │   ├── habr-html-1.sublime-project
    │   │   ├── habr-html-1.sublime-workspace
    │   │   ├── img
    │   │   │   ├── bg.png
    │   │   │   ├── footer-logo.png
    │   │   │   ├── h1-bg.png
    │   │   │   ├── logo.png
    │   │   │   ├── sample.png
    │   │   │   ├── social.png
    │   │   │   └── social-small.png
    │   │   ├── index.html
    │   │   ├── js
    │   │   │   ├── main.js
    │   │   │   ├── plugins.js
    │   │   │   └── vendor
    │   │   │       ├── jquery-1.12.0.min.js
    │   │   │       └── modernizr-2.8.3.min.js
    │   │   └── README.md
    │   ├── [Habr] Single-page layout 2 (bootstrap)
    │   │   ├── bower.json
    │   │   ├── gruntfile.js
    │   │   ├── less
    │   │   │   ├── styles.less
    │   │   │   └── variables.less
    │   │   ├── package.json
    │   │   ├── README.md
    │   │   ├── test.sublime-project
    │   │   ├── test.sublime-workspace
    │   │   └── www
    │   │       ├── css
    │   │       │   ├── bootstrap.css
    │   │       │   ├── main.css
    │   │       │   └── normalize.css
    │   │       ├── fonts
    │   │       │   ├── glyphicons-halflings-regular.eot
    │   │       │   ├── glyphicons-halflings-regular.svg
    │   │       │   ├── glyphicons-halflings-regular.ttf
    │   │       │   ├── glyphicons-halflings-regular.woff
    │   │       │   └── glyphicons-halflings-regular.woff2
    │   │       ├── img
    │   │       │   ├── about-1.png
    │   │       │   ├── about-2.png
    │   │       │   ├── bg.png
    │   │       │   ├── footer-logo.png
    │   │       │   ├── h1-bg.png
    │   │       │   ├── logo.png
    │   │       │   ├── map.png
    │   │       │   ├── sample.png
    │   │       │   ├── social.png
    │   │       │   ├── social-small.png
    │   │       │   ├── source
    │   │       │   │   ├── About.psd
    │   │       │   │   ├── Homepage.psd
    │   │       │   │   ├── Projects.psd
    │   │       │   │   └── Read Me.txt
    │   │       │   └── team
    │   │       │       ├── Brunton.jpg
    │   │       │       ├── Doe.jpg
    │   │       │       ├── Nobriga.jpg
    │   │       │       ├── Pittsley.jpg
    │   │       │       ├── Rousselle.jpg
    │   │       │       ├── Shoff.jpg
    │   │       │       ├── Simser.jpg
    │   │       │       ├── Tondrea.jpg
    │   │       │       ├── Venuti.jpg
    │   │       │       └── Wollman.jpg
    │   │       ├── index.html
    │   │       └── js
    │   │           ├── main.js
    │   │           ├── plugins.js
    │   │           └── vendor
    │   │               ├── bootstrap.min.js
    │   │               ├── jquery-1.12.0.min.js
    │   │               └── modernizr-2.8.3.min.js
    │   └── [pluralsight] Bootstrap
    │       ├── bootstrap.sublime-project
    │       ├── bootstrap.sublime-workspace
    │       ├── Gruntfile.js
    │       ├── package.json
    │       ├── README.md
    │       ├── server.js
    │       └── www
    │           ├── About.html
    │           ├── Contact.html
    │           ├── css
    │           │   ├── amelia-bootstrap.min.css
    │           │   ├── bootstrap.css
    │           │   ├── bootstrap.css.map
    │           │   ├── bootstrap.min.css
    │           │   ├── bootstrap.min.css.map
    │           │   ├── bootstrap-theme.css
    │           │   ├── bootstrap-theme.css.map
    │           │   ├── bootstrap-theme.min.css
    │           │   ├── bootstrap-theme.min.css.map
    │           │   └── site.css
    │           ├── fonts
    │           │   ├── glyphicons-halflings-regular.eot
    │           │   ├── glyphicons-halflings-regular.svg
    │           │   ├── glyphicons-halflings-regular.ttf
    │           │   ├── glyphicons-halflings-regular.woff
    │           │   └── glyphicons-halflings-regular.woff2
    │           ├── images
    │           │   ├── carousel-1.jpg
    │           │   ├── carousel-2.jpg
    │           │   ├── carousel-3.jpg
    │           │   ├── carousel-4.jpg
    │           │   ├── lebowski-1.jpg
    │           │   ├── lebowski-2.jpg
    │           │   └── lebowski-3.jpg
    │           ├── Index.html
    │           ├── js
    │           │   ├── bootstrap.js
    │           │   ├── bootstrap.min.js
    │           │   ├── jquery-2.0.3.js
    │           │   ├── jquery-2.0.3.min.js
    │           │   ├── npm.js
    │           │   └── site.js
    │           └── test.html
    ├── JS
    │   └── dnd
    │       ├── binDropZone.js
    │       ├── binDropZoneWrapper.js
    │       ├── dnd.css
    │       ├── dragManager.css
    │       ├── dragManager.js
    │       ├── dragObject.js
    │       ├── dragZone.js
    │       ├── dragZoneWrapper.js
    │       ├── dropZone.js
    │       ├── dropZoneWrapper.js
    │       ├── helpers.js
    │       ├── img
    │       │   ├── JS_DnD_Activity_Diagram.png
    │       │   └── JS_DnD_Collaboration_Diagram.png
    │       ├── index.html
    │       ├── README.md
    │       ├── treeDragObject.js
    │       ├── treeDragZone.js
    │       └── treeDropZone.js
    ├── [Mail.ru] Frontend
    │   ├── Gruntfile.js
    │   ├── package.json
    │   ├── public_html
    │   │   ├── css
    │   │   │   ├── fonts
    │   │   │   │   ├── glyphicons-halflings-regular.eot
    │   │   │   │   ├── glyphicons-halflings-regular.svg
    │   │   │   │   ├── glyphicons-halflings-regular.ttf
    │   │   │   │   ├── glyphicons-halflings-regular.woff
    │   │   │   │   └── glyphicons-halflings-regular.woff2
    │   │   │   ├── main.css
    │   │   │   └── vendor
    │   │   │       ├── bootstrap.min.css
    │   │   │       └── bootstrap-theme.min.css
    │   │   ├── index.html
    │   │   ├── js
    │   │   │   ├── app
    │   │   │   │   ├── index.js
    │   │   │   │   ├── sandbox.js
    │   │   │   │   └── sandbox_tmpl
    │   │   │   │       └── player.js
    │   │   │   ├── collections
    │   │   │   │   └── users.js
    │   │   │   ├── main.js
    │   │   │   ├── models
    │   │   │   │   └── user.js
    │   │   │   ├── router.js
    │   │   │   ├── tmpl
    │   │   │   │   ├── game.js
    │   │   │   │   ├── gamelist.js
    │   │   │   │   ├── login.js
    │   │   │   │   └── main.js
    │   │   │   ├── vendor
    │   │   │   │   ├── backbone.js
    │   │   │   │   ├── bootstrap.js
    │   │   │   │   ├── jquery.js
    │   │   │   │   ├── require.js
    │   │   │   │   └── underscore.js
    │   │   │   └── views
    │   │   │       ├── game.js
    │   │   │       ├── gamelist.js
    │   │   │       ├── login.js
    │   │   │       └── main.js
    │   │   └── tests
    │   │       ├── index.html
    │   │       ├── qunit.css
    │   │       ├── qunit.js
    │   │       └── tests.js
    │   ├── README.md
    │   ├── _sandbox
    │   │   ├── css
    │   │   │   ├── main.css
    │   │   │   └── normalize.css
    │   │   ├── index.html
    │   │   └── js
    │   │       ├── main.js
    │   │       ├── plugins.js
    │   │       └── vendor
    │   │           ├── jquery-1.12.0.min.js
    │   │           └── modernizr-2.8.3.min.js
    │   ├── server.js
    │   ├── server_tml
    │   │   └── authresponse.txt
    │   └── templates
    │       ├── gamelist.xml
    │       ├── game.xml
    │       ├── login.xml
    │       ├── main.xml
    │       └── sandbox
    │           └── player.xml
    ├── [Mail.ru] Web Applications
    │   ├── news_portal
    │   │   ├── comments
    │   │   │   ├── admin.py
    │   │   │   ├── apps.py
    │   │   │   ├── forms.py
    │   │   │   ├── __init__.py
    │   │   │   ├── migrations
    │   │   │   │   ├── 0001_initial.py
    │   │   │   │   ├── 0002_auto_20160521_1546.py
    │   │   │   │   ├── 0003_auto_20160528_1639.py
    │   │   │   │   └── __init__.py
    │   │   │   ├── models.py
    │   │   │   ├── tests.py
    │   │   │   └── views.py
    │   │   ├── config-cent.json
    │   │   ├── core
    │   │   │   ├── admin.py
    │   │   │   ├── apps.py
    │   │   │   ├── forms.py
    │   │   │   ├── __init__.py
    │   │   │   ├── migrations
    │   │   │   │   ├── 0001_initial.py
    │   │   │   │   ├── 0002_auto_20160528_1639.py
    │   │   │   │   └── __init__.py
    │   │   │   ├── models.py
    │   │   │   ├── settings.py
    │   │   │   ├── static
    │   │   │   │   └── core
    │   │   │   │       ├── base.css
    │   │   │   │       ├── base.js
    │   │   │   │       ├── centrifuge.js
    │   │   │   │       ├── chosen.css
    │   │   │   │       ├── chosen.jquery.js
    │   │   │   │       ├── chosen-sprite@2x.png
    │   │   │   │       ├── chosen-sprite.png
    │   │   │   │       └── Earth.png
    │   │   │   ├── templates
    │   │   │   │   ├── admin
    │   │   │   │   │   └── base_site.html
    │   │   │   │   ├── base.html
    │   │   │   │   ├── login.html
    │   │   │   │   └── signup.html
    │   │   │   ├── urls.py
    │   │   │   ├── views.py
    │   │   │   └── wsgi.py
    │   │   ├── db.sqlite3
    │   │   ├── environment.yml
    │   │   ├── hello
    │   │   │   ├── admin.py
    │   │   │   ├── apps.py
    │   │   │   ├── __init__.py
    │   │   │   ├── migrations
    │   │   │   │   └── __init__.py
    │   │   │   ├── models.py
    │   │   │   ├── templates
    │   │   │   │   └── hello.html
    │   │   │   ├── tests.py
    │   │   │   ├── urls.py
    │   │   │   └── views.py
    │   │   ├── manage.py
    │   │   ├── news
    │   │   │   ├── admin.py
    │   │   │   ├── apps.py
    │   │   │   ├── forms.py
    │   │   │   ├── __init__.py
    │   │   │   ├── management
    │   │   │   │   ├── commands
    │   │   │   │   │   ├── __init__.py
    │   │   │   │   │   └── recount_likes.py
    │   │   │   │   └── __init__.py
    │   │   │   ├── migrations
    │   │   │   │   ├── 0001_initial.py
    │   │   │   │   ├── 0002_auto_20160515_1856.py
    │   │   │   │   ├── 0003_article_rating.py
    │   │   │   │   ├── 0004_articlelike.py
    │   │   │   │   ├── 0005_auto_20160526_1046.py
    │   │   │   │   ├── 0006_articlelike_is_liked.py
    │   │   │   │   ├── 0007_auto_20160527_1004.py
    │   │   │   │   ├── 0008_article_is_published.py
    │   │   │   │   ├── 0009_auto_20160528_1124.py
    │   │   │   │   ├── 0010_auto_20160531_2141.py
    │   │   │   │   ├── 0011_auto_20160531_2201.py
    │   │   │   │   ├── 0012_auto_20160531_2202.py
    │   │   │   │   ├── 0013_auto_20160531_2252.py
    │   │   │   │   ├── 0014_auto_20160602_0912.py
    │   │   │   │   ├── 0015_auto_20160602_0940.py
    │   │   │   │   └── __init__.py
    │   │   │   ├── models.py
    │   │   │   ├── static
    │   │   │   │   └── news
    │   │   │   │       ├── comments_subscribe.js
    │   │   │   │       └── like_button.js
    │   │   │   ├── templates
    │   │   │   │   └── news
    │   │   │   │       ├── article.html
    │   │   │   │       ├── create.html
    │   │   │   │       ├── like_button.html
    │   │   │   │       └── list.html
    │   │   │   ├── tests.py
    │   │   │   ├── urls.py
    │   │   │   └── views.py
    │   │   ├── README.md
    │   │   ├── requirements.txt
    │   │   ├── techsupport
    │   │   │   ├── admin.py
    │   │   │   ├── apps.py
    │   │   │   ├── forms.py
    │   │   │   ├── __init__.py
    │   │   │   ├── migrations
    │   │   │   │   └── __init__.py
    │   │   │   ├── models.py
    │   │   │   ├── templates
    │   │   │   │   └── techsupport
    │   │   │   │       └── report_error.html
    │   │   │   ├── templatetags
    │   │   │   │   ├── form_extras.py
    │   │   │   │   └── __init__.py
    │   │   │   ├── tests.py
    │   │   │   └── views.py
    │   │   └── tictactoe
    │   │       ├── admin.py
    │   │       ├── apps.py
    │   │       ├── forms.py
    │   │       ├── __init__.py
    │   │       ├── migrations
    │   │       │   ├── 0001_initial.py
    │   │       │   ├── 0002_auto_20160528_1654.py
    │   │       │   ├── 0003_auto_20160528_1739.py
    │   │       │   ├── 0004_auto_20160528_1848.py
    │   │       │   ├── 0005_auto_20160528_1911.py
    │   │       │   ├── 0006_auto_20160531_2141.py
    │   │       │   └── __init__.py
    │   │       ├── models.py
    │   │       ├── templates
    │   │       │   └── tictactoe
    │   │       │       ├── accept_invitation.html
    │   │       │       ├── game.html
    │   │       │       ├── game_list_snippet.html
    │   │       │       ├── invitation.html
    │   │       │       ├── list_snippet.html
    │   │       │       └── move.html
    │   │       ├── tests.py
    │   │       ├── urls.py
    │   │       └── views.py
    │   └── tcp_servers
    │       ├── async.py
    │       ├── client.py
    │       ├── fork.py
    │       ├── __init__.py
    │       ├── itportal.conf
    │       ├── mipt.conf
    │       ├── nginx.conf
    │       ├── prefork.py
    │       ├── simple_http.py
    │       ├── simple.py
    │       └── stackoverflow.conf
    ├── [MIPT] Machine Learning
    │   ├── dataset.tsv
    │   ├── example_koi_8.txt
    │   ├── example_utf8.txt
    │   ├── file_to_write_in.txt
    │   ├── nbmerge.py
    │   ├── second_file_for_write_in.txt
    │   ├── updated_dataset.csv
    │   ├── w1.ipynb
    │   ├── w2.ipynb
    │   ├── w3_matrix_operations.ipynb
    │   ├── w3_vector_operations.ipynb
    │   └── w4_stochastic_variables.ipynb
    ├── NodeJS
    │   ├── ajax-test
    │   │   ├── fileUploader.js
    │   │   ├── index.html
    │   │   ├── load-digits.js
    │   │   ├── load-phones.js
    │   │   ├── package.json
    │   │   ├── phones.json
    │   │   ├── README.md
    │   │   ├── server.js
    │   │   ├── uploader.js
    │   │   └── upload.js
    │   ├── express-test
    │   │   ├── app.js
    │   │   ├── config
    │   │   │   ├── config.json
    │   │   │   └── index.js
    │   │   ├── db.js
    │   │   ├── errors
    │   │   │   └── index.js
    │   │   ├── libs
    │   │   │   ├── index.js
    │   │   │   ├── logger.js
    │   │   │   ├── mongoose.js
    │   │   │   └── sessionStore.js
    │   │   ├── middleware
    │   │   │   ├── checkAuth.js
    │   │   │   ├── hitCounter.js
    │   │   │   ├── loadUser.js
    │   │   │   └── sendHttpError.js
    │   │   ├── models
    │   │   │   └── user.js
    │   │   ├── package.json
    │   │   ├── README.md
    │   │   ├── routes
    │   │   │   ├── chat.js
    │   │   │   ├── index.js
    │   │   │   ├── login.js
    │   │   │   ├── logout.js
    │   │   │   └── users.js
    │   │   ├── scripts
    │   │   │   ├── async.js
    │   │   │   ├── mongodb-test.js
    │   │   │   ├── mongoose-test.js
    │   │   │   └── mongoose-test-v2.js
    │   │   ├── socket
    │   │   │   └── index.js
    │   │   ├── views
    │   │   │   ├── chat.ejs
    │   │   │   ├── error.ejs
    │   │   │   ├── index.ejs
    │   │   │   ├── layout
    │   │   │   │   └── page.ejs
    │   │   │   ├── login.ejs
    │   │   │   └── partials
    │   │   │       └── nav.ejs
    │   │   └── webapp
    │   │       ├── css
    │   │       │   └── app.css
    │   │       └── js
    │   │           ├── chat.js
    │   │           ├── login.js
    │   │           └── logout.js
    │   ├── longpoll-test
    │   │   ├── browser.js
    │   │   ├── index.html
    │   │   └── server.js
    │   ├── mocha-test
    │   │   ├── browser
    │   │   │   ├── index.html
    │   │   │   ├── mocha.css
    │   │   │   ├── mocha.js
    │   │   │   └── tests.js
    │   │   ├── config.json
    │   │   ├── gulpfile.js
    │   │   ├── lib
    │   │   │   ├── getPalette.js
    │   │   │   └── hex2rgb.js
    │   │   ├── package.json
    │   │   ├── README.md
    │   │   ├── server.js
    │   │   ├── test
    │   │   │   ├── fixtures
    │   │   │   │   └── config-not-array.json
    │   │   │   ├── getPalette.test.bad.js
    │   │   │   ├── getPalette.test.expect.js
    │   │   │   ├── getPalette.test.js
    │   │   │   ├── getPalette.test.should.js
    │   │   │   ├── hex2rgb.test.expect.js
    │   │   │   ├── hex2rgb.test.js
    │   │   │   ├── hex2rgb.test.should.js
    │   │   │   └── mocha.opts
    │   │   └── views
    │   │       └── index.jade
    │   └── nodejs-test
    │       ├── chat-server.js
    │       ├── demo
    │       │   ├── async.js
    │       │   ├── console.js
    │       │   ├── ee.js
    │       │   ├── error.js
    │       │   ├── leak.js
    │       │   ├── modules
    │       │   │   ├── app.js
    │       │   │   ├── db
    │       │   │   │   ├── index.js
    │       │   │   │   └── ru.json
    │       │   │   ├── logger.js
    │       │   │   ├── server.js
    │       │   │   └── user
    │       │   │       └── index.js
    │       │   ├── pow.js
    │       │   ├── streams.js
    │       │   └── util.js
    │       ├── echo.js
    │       ├── package.json
    │       ├── public
    │       │   ├── index.html
    │       │   └── long-poll.js
    │       ├── README.md
    │       ├── server.js
    │       └── serve-static.js
    ├── [pluralsight] Python Beyond the Basics
    │   ├── 01 - Packaging.ipynb
    │   ├── reader
    │   │   ├── compressed
    │   │   │   ├── bzipped.py
    │   │   │   ├── gzipped.py
    │   │   │   ├── __init__.py
    │   │   │   └── __main__.py
    │   │   ├── __init__.py
    │   │   └── reader.py
    │   ├── reader_exec
    │   │   ├── __main__.py
    │   │   └── reader
    │   │       ├── compressed
    │   │       │   ├── bzipped.py
    │   │       │   ├── gzipped.py
    │   │       │   ├── __init__.py
    │   │       │   └── __main__.py
    │   │       ├── __init__.py
    │   │       └── reader.py
    │   └── test.bz2
    ├── [pluralsight] Python fundamentals
    │   ├── 01-05 - Basics.ipynb
    │   ├── 03,06 - strings and collections.ipynb
    │   ├── 07 - exception handling.ipynb
    │   ├── 08 - Iterables.ipynb
    │   ├── 09 - classes
    │   │   └── airtravel.py
    │   ├── 10 - File and resource management
    │   │   ├── 10 - File and Resource management.ipynb
    │   │   ├── bmp.py
    │   │   ├── files.py
    │   │   ├── fractal.py
    │   │   ├── fridge.py
    │   │   ├── recaman.dat
    │   │   ├── recaman.py
    │   │   ├── series.py
    │   │   └── wasteland.txt
    │   ├── 11 - Testing and Shipping
    │   │   ├── palindrome
    │   │   │   ├── palindrome.py
    │   │   │   └── setup.py
    │   │   └── text_analyzer.py
    │   ├── exceptional.py
    │   ├── generator.py
    │   ├── roots.py
    │   └── words.py
    └── [Stanford] Compilers
        ├── assignments
        │   ├── PA2
        │   │   ├── cool.flex
        │   │   ├── cool-lex.cc
        │   │   ├── cool-lex.d
        │   │   ├── escapednull.cool
        │   │   ├── escapednull.out
        │   │   ├── handle_flags.cc
        │   │   ├── handle_flags.d
        │   │   ├── hello_world.cl
        │   │   ├── lextest.cc
        │   │   ├── lextest.d
        │   │   ├── mycoolc
        │   │   ├── octal.cool
        │   │   ├── octal.out
        │   │   ├── pa1-grading.pl
        │   │   ├── README
        │   │   ├── stringtab.cc
        │   │   ├── stringtab.d
        │   │   ├── test.cl
        │   │   ├── test.err
        │   │   ├── test.out
        │   │   ├── utilities.cc
        │   │   └── utilities.d
        │   ├── PA3
        │   │   ├── bad.cl
        │   │   ├── bison-test
        │   │   │   ├── calc
        │   │   │   ├── calc_simple.tab.c
        │   │   │   ├── calc_simple.y
        │   │   │   ├── calc.tab.c
        │   │   │   ├── calc.y
        │   │   │   ├── mfcalc
        │   │   │   ├── mfcalc.c
        │   │   │   ├── mfcalc.h
        │   │   │   ├── mfcalc.tab.c
        │   │   │   ├── mfcalc.tab.h
        │   │   │   ├── mfcalc.y
        │   │   │   ├── non-slr.tab.c
        │   │   │   ├── non-slr.y
        │   │   │   ├── rpcalc
        │   │   │   ├── rpcalc.tab.c
        │   │   │   ├── rpcalc.y
        │   │   │   ├── simple.tab.c
        │   │   │   └── simple.y
        │   │   ├── cool-parse.cc
        │   │   ├── cool-parse.d
        │   │   ├── cool.tab.h
        │   │   ├── cool-tree.cc
        │   │   ├── cool-tree.d
        │   │   ├── cool-tree.handcode.h
        │   │   ├── cool.y
        │   │   ├── dumptype.cc
        │   │   ├── dumptype.d
        │   │   ├── good.cl
        │   │   ├── handle_flags.cc
        │   │   ├── handle_flags.d
        │   │   ├── mycoolc
        │   │   ├── myparser
        │   │   ├── pa2-grading.pl
        │   │   ├── parser-phase.cc
        │   │   ├── parser-phase.d
        │   │   ├── README
        │   │   ├── stringtab.cc
        │   │   ├── stringtab.d
        │   │   ├── tokens-lex.cc
        │   │   ├── tokens-lex.d
        │   │   ├── tree.cc
        │   │   ├── tree.d
        │   │   ├── utilities.cc
        │   │   └── utilities.d
        │   └── PA4
        │       ├── q2.coolc
        │       ├── q2.s
        │       ├── q4.coolc
        │       ├── q4.s
        │       ├── q6.coolc
        │       └── q6.s
        ├── cool-jison
        │   ├── arith.cl
        │   ├── bad2.cl
        │   ├── badblock.cl
        │   ├── bad.cl
        │   ├── cool.flex
        │   ├── cool-gho.js
        │   ├── cool-gho-old.js
        │   ├── cool.js
        │   ├── cool_.js
        │   ├── cool-lex.js
        │   ├── cool-new.y
        │   ├── cool.output2
        │   ├── cool.y
        │   ├── escapednull.cool
        │   ├── escapedquote.cool
        │   ├── firstclasserrored.cl
        │   ├── hello_world.cl
        │   ├── index.js
        │   ├── invalidcharacters.cool
        │   ├── life.cl
        │   ├── null_in_code.cl.cool
        │   ├── null_in_string.cl.cool
        │   ├── null_in_string_followed_by_tokens.cl.cool
        │   ├── package.json
        │   └── README.md
        └── README.md

135 directories, 608 files
```

I think all these don't belong into the distributed package and should be removed.

FWIW, the sha256 of the package I got is:

```
5ead101834c35cc1dc89b3e545746390e828bdbde15506d1c92aa9c8101ec65e  jison-gho-0.6.1-215.tgz
```

**Comment by sciurus** [comment] 2019-01-17 17:40
They're not all in the tmp2 folder. It also contains a `.git` file which it should not.

```
$ cat node_modules/jison-gho/.git
gitdir: ../../../.git/modules/lib/modules/tooling/jison
```

**Comment by ductiletoaster** [comment] 2019-01-17 19:00
Not sure if this is related but our CI process ran into this due to a dependency of this package.
```
+ git clean -fdx
fatal: Not a git repository: node_modules/@gerhobbelt/recast/../../../.git/modules/lib/modules/js/recast
```
Seems the version of recast this package uses has a dependency with a .git file in it. Confirmed that later versions don't have this issue.

**Comment by GerHobbelt** [comment] 2019-04-14 16:30
A new `jison-gho` package version has been published on `npm` today to fix this issue. It's regrettable y'all had to wait so long for this. 😢  

(Note: `jison -v` still reports itself as 0.6.1-215 instead of 0.6.1-216 as this is a patched release purely for this issue. Only package.json has been updated to the new build number.)

**Comment by GerHobbelt** [comment] 2019-04-14 16:35
For those interested in some odd background about this: `jison-gho` is developed on a Windows dev machine with msys, etc. and I finally found what's going wrong with the .gitignore and .npmignore files there. It's odd, but here's an extract of the new .npmignore file:

```
## WARNING ## WARNING ## WARNING ## WARNING ## WARNING
##
## Looks like npm (and git?) has a bug on Windows where the fnmatch pattern with 
## trailing slash, e.g. `output/`, doesn't work for subdirectories, while the same pattern 
## *without* the trailing slash *does* work for filtering directories (behaviour like 
## `**/tmp/` but git and npm supports a different set of glob patterns)
##
## Commandline to observe this behaviour (on Windows dev box):
##
##     npm pack && tar ftv *.tgz | grep tests
##
## Edit the ignore file to edit the `tests` line further below with or without trailing `/` to 
## observe the buggy behaviour.
##
## WARNING ## WARNING ## WARNING ## WARNING ## WARNING

...

# scratch space
#tmp/
#---^ see WARNING at the top of this file!
tmp

# additional crap thast shouldn't land in git repo or npm:
#tmp*/
#---^ see WARNING at the top of this file!
tmp*
```

**Comment by GerHobbelt** [comment] 2019-06-04 19:55
Closing this as solved due to https://github.com/GerHobbelt/jison/issues/43#issuecomment-483011578

**Closed by GerHobbelt** 2019-06-04 19:55 UTC
